### ISSUE TITLE
Help with this plugin

### ISSUE THREAD

**Issue by passionetartufo** [TypesettingTools/AI2ASS#3]
Hi.
I just installed your plugin for Ai.
This is the sign i would like to design: http://s3.postimg.org/w9suvpmoj/sign1.jpg

This is the gradient I made on Ai: http://s3.postimg.org/5d8vne3v7/sign2.jpg

But when I use your plugin and I copy the script on Aegisub. I get this orrible effect: http://s3.postimg.org/zf8v86fwz/sign3.jpg

Copuld you please tell me how toremove that horrible black stripes? Thank you

**Comment by line0** [comment]
You actually uncovered a little bug there, which is an additional black backplane being added to the output.

However, removing it will not solve your issue. The purpose of AI2ASS is to export AI drawings to ASS, not to make things look pretty within the constraints of ASS rendering. When you expand your gradient, AI will turn it into  small color strips that are directly adjacent to each other, but don't overlap. 
This will cause you to run into subpixel rendering and anti-aliasing issues with xy-sub/vsfilter and libass and that is even before you apply an blur to the sign.

There are a few ways to fix this:
- Expand the color strips by a few pixels using the AI offset tool or my [Extend Paths](https://github.com/TypesettingTools/line0-Illustrator-Scripts/blob/master/Extend%20Paths.jsx) script. While you're at it, use the [Apply Clips](https://github.com/TypesettingTools/line0-Illustrator-Scripts/blob/master/Apply%20Clips.jsx) script to allow your sign edges to be blurred and to increase rendering efficiency.
- Write a script that exports gradients in the same way that [Gradient Everything](https://github.com/TypesettingTools/lyger-Aegisub-Scripts/blob/master/macros/lyger.GradientEverything.moon) does. You can achieve this by swapping fill and clip (either in AI or with an Aegisub automation script on the AI2ASS output), however you will have to make the clips either overlap by a bit or make sure the paths [only go along pixel boundaries](http://www.cccp-project.net/forums/index.php?topic=5976.msg44059#msg44059). Obviously this will only work for straight horizontal or vertical gradients.
- Write a script that layers the color strips with full overlap, i.e. make first strip cover the whole shape, the second the whole shape excluding the desired final width of the first strip and continue until the last strip is only a tiny sliver. This will get you quite clean gradients, especially with large blurs. The downside is that you'll end up with non-uniformly blurred shape edges and any kind of transparency won't work. 

Please take note this is not a typesetting support forum, so this is not the right place to explore the topic of gradients any further. That said, I'll keep the issue open for now until we have a fix for the additional black shape issue.
