### ISSUE TITLE
Not working in AI CS6

### ISSUE THREAD

**Issue by pendave** [TypesettingTools/AI2ASS#6]
I have no idea why it does not work.

![3ff gh 5u 1qo 8wciqu](https://cloud.githubusercontent.com/assets/1331881/17844882/68b75042-6870-11e6-84cb-de5261f6e0eb.png)

**Comment by torque** [comment]
I also have no idea why it does not work.

**Comment by line0** [comment]
count me in 
(some kind of error message or description of broken behavior would be useful)

**Comment by CoffeeFlux** [comment]
same

**Comment by CoffeeFlux** [comment]
On a more serious note, can you provide the platform, ai file it fails on, more details about how often it fails, etc? This isn't a lot to go off.
